"""add_biometrics_foto_and_is_bodyweight

Revision ID: 3e06258d134a
Revises: 
Create Date: 2026-09-04 23:57:54.976144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e06258d134a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_bodyweight', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('foto_perfil', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'foto_perfil')
    op.drop_column('exercises', 'is_bodyweight')
    # ### end Alembic commands ###
