"""add_biometrics_foto_and_is_bodyweight

Revision ID: 3e06258d134a
Revises: 
Create Date: 2026-09-04 23:57:54.976144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e06258d134a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_bodyweight', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_constraint(op.f('routines_share_hash_key'), 'routines', type_='unique')
    op.create_index(op.f('ix_routines_share_hash'), 'routines', ['share_hash'], unique=True)
    op.alter_column('scheduled_workouts', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_scheduled_workouts_invited_by_id'), 'scheduled_workouts', ['invited_by_id'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_routine_id'), 'scheduled_workouts', ['routine_id'], unique=False)
    op.add_column('users', sa.Column('foto_perfil', sa.String(length=500), nullable=True))
    op.alter_column('users', 'share_calendar_with_friends',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'extra_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('users', 'share_calendar_with_friends',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('users', 'foto_perfil')
    op.drop_index(op.f('ix_scheduled_workouts_routine_id'), table_name='scheduled_workouts')
    op.drop_index(op.f('ix_scheduled_workouts_invited_by_id'), table_name='scheduled_workouts')
    op.alter_column('scheduled_workouts', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_routines_share_hash'), table_name='routines')
    op.create_unique_constraint(op.f('routines_share_hash_key'), 'routines', ['share_hash'])
    op.drop_column('exercises', 'is_bodyweight')
    # ### end Alembic commands ###
